apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
  labels:
    app: course
spec:
  replicas: 1
  template:
    metadata:
      name: course
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: klaa79/course
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube 
      restartPolicy: Always
  selector:
    matchLabels:
      app: course
