apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
  labels:
    app: video
spec:
  replicas: 1
  template:
    metadata:
      name: video
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: klaa79/video
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube 
      restartPolicy: Always
  selector:
    matchLabels:
      app: video
