server:
  port: 8096
spring:
  application:
    name: documents
  banner:
    location: banner.txt
  data:
    mongodb:
      password: password
      username: root
      database: documents
      port: 27017
      host: mongo
      authentication-database: admin

  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: host.docker.internal:9092
management:
  tracing:
    sampling:
      probability: 1.0

