services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
#  keycloak:
#    container_name: keycloak-bsn
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9099:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - klaa
#    command:
#      - "start-dev"
  ffmpeg:
    container_name: b2c-ffmpeg
    image: jrottenberg/ffmpeg:latest
    networks:
      - b2c
    ports:
      - "29002:29000"
    tty: true
    volumes:
      - "Z:/springprojects/KLAAschool/videos/src/main/resources/assets:/app/assets"
      - "Z:/springprojects/KLAAschool/videos/src/main/resources/hsl_dir:/app/hsl_dir"
    environment:
      - FFREPORT=file=/tmp/ffmpeg_report.log:level=32
      - ASSETS_DIR=/app/assets
      - HLS_DIR=/app/hsl_dir
    entrypoint: "/bin/bash"






networks:
  postgres:
    driver: bridge
  klaa:
    driver: bridge
  b2c:
    driver: bridge







volumes:
  postgres:
  pgadmin:
  keycloak:
    driver: local