server:
  port: 8090
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8099/realms/klaa
  banner:
    location: banner.txt

  cloud:
    gateway:
      routes:
        - id: staff
          uri: lb://STAFF
          predicates:
            - Path= /api/v1/staffs/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path= /api/v1/notifications/**
        - id: courses
          uri: lb://COURSES
          predicates:
            - Path= /api/v1/courses/**
        - id: user
          uri: lb://USER
          predicates:
            - Path= /api/v1/users/**
        - id: video
          uri: lb://VIDEO
          predicates:
            - Path= /api/v1/videos/**
        - id: documents
          uri: lb://DOCUMENTS
          predicates:
            - Path= /api/v1/documents/**
    compatibility-verifier:
      enabled: false




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/