server:
  port: 8086
spring:
  application:
    name: api-gateway
  banner:
    location: banner.txt
  cloud:
    gateway:
      routes:
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path= /api/v1/students/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/