server:
  port: 8086
spring:
  application:
    name: api-gateway
  banner:
    location: banner.txt
  cloud:
    gateway:
      routes:
        - id: student
          uri: lb://STUDENT
          predicates:
            - Path= /api/v1/students/**
        - id: teacher
          uri: lb://TEACHER
          predicates:
            - Path= /api/v1/teachers/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path= /api/v1/notifications/**
        - id: course
          uri: lb://COURSE
          predicates:
            - Path= /api/v1/courses/**
        - id: user
          uri: lb://USER
          predicates:
            - Path= /api/v1/users/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/