server:
  port: 8091
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
      max-request-size: 50MB
  application:
    name: courses
  banner:
    location: banner.txt
  data:
    mongodb:
      password: password
      username: root
      database: courses
      port: 27017
      host: mongo
      authentication-database: admin
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: host.docker.internal:9092
management:
  tracing:
    sampling:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: false

