spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mouatazgpt79@gmail.com
    password: yomquyvilnkzoegu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
           enable: true

management:
  tracing:
    sampling:
      probability: 1.0