server:
  port: 8093
spring:
  application:
    name: notification
  banner:
    location: banner.txt
  data:
    mongodb:
      password: password
      username: root
      database: notifications
      port: 27017
      host: localhost
      authentication-database: admin
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



