apiVersion: apps/v1
kind: Deployment
metadata:
  name: document
  labels:
    app: document
spec:
  replicas: 1
  template:
    metadata:
      name: document
      labels:
        app: document
    spec:
      containers:
        - name: document
          image: klaa79/documents
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
  selector:
    matchLabels:
      app: document
