apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  replicas: 1
  template:
    metadata:
      name: aggregator
      labels:
        app: aggregator
    spec:
      containers:
        - name: staff
          image: klaa79/aggregator
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: k8s
      restartPolicy: Always
  selector:
    matchLabels:
      app: aggregator