server:
  port: 8089
  error:
    include-message: always
  http2:
    enabled: true
spring:
  application:
    name: video
  banner:
    location: banner.txt
  data:
    mongodb:
      password: password
      username: root
      database: videoinfo
      port: 27017
      host: localhost
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 2100MB
      max-request-size: 2100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
grpc:
  server:
    port: 8084



