server:
  port: 8089
spring:
  application:
    name: video
  banner:
    location: banner.txt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
grpc:
  server:
    port: 8084