server:
  port: 8090
spring:
  application:
    name: staff
  zipkin:
    base-url: http://localhost:9411
  banner:
    location: banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/staff
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/